name: subscribes-backend
services:
  pg:
    image: postgres:17.4-alpine
    container_name: subscribes-pg
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "subscribes-pg:/var/lib/postgresql/data"
    restart: always
  app:
    container_name: subscribes-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      pg:
        condition: service_healthy
    environment:
      TZ: UTC
    env_file:
      - path: ".env"
        required: false
    restart: always

volumes:
  subscribes-pg:
